# Podfile
platform :ios, '8.0'
use_frameworks!

# Network
pod 'Alamofire', '~> 3.1.1'

# Rx
pod 'RxSwift', '~> 2.0.0-beta.3'
pod 'RxCocoa', '~> 2.0.0-beta.3'
pod 'RxBlocking', '~> 2.0.0-beta.3'

# Map
pod 'ObjectMapper', '~> 0.1'

# Realm
pod 'RealmSwift', '~> 0.96'
