# Podfile
platform :ios, '8.0'
use_frameworks!

# Network
pod 'Alamofire', '~> 3.1.1'

# Rx
pod 'RxSwift', '~> 2.1.0'
pod 'RxCocoa', '~> 2.1.0'
pod 'RxBlocking', '~> 2.1.0'

# Map
pod 'ObjectMapper', '~> 1.0'

# Realm
pod 'RealmSwift', '~> 0.97.0'
