# Podfile
platform :ios, '8.0'
use_frameworks!

# Network
pod 'Alamofire', '~> 3.1.1'

# Rx
pod 'RxSwift', '~> 2.0.0-beta.2'
pod 'RxCocoa', '~> 2.0.0-beta.2'
pod 'RxBlocking', '~> 2.0.0-beta.2'

# Map
pod 'ObjectMapper', '~> 0.17'
