source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

# === taktem Original Library ===
pod 'TaktemSwiftSupport', :git => 'https://github.com/taktem/TaktemSwiftSupport.git', :tag => '1.0.1'